docs_dir: content
nav:
- DataSource: datasource.md
- RatingSystem: ratingsystem.md
- Predictor: predictor.md
- Game: game.md
- GameStats: gamestats.md
- Prediction: prediction.md
- Rating: rating.md
- Stat: stat.md
- TeamRating: team_rating.md
site_name: My Project
